### ISSUE TITLE
Capture --binary results

### ISSUE THREAD

**Issue by luigixx73** [open-pdf-sign/open-pdf-sign-node#1]
There should be a return with stdout binary results if --binary option is enabled to capture the buffer and work with it if you don't want to open the output file for such purpose.

**Comment by cproof** [comment]
Thank you for the suggestion, then it should suffice if the invocation resolves with the `stdout` as a Buffer object. I'll look into that.

**Comment by cproof** [comment]
finally closed with the newly released `v0.1.7`
